apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sleep", "3600"]  # Keeps the container running
